### ISSUE TITLE
Build failing with LibreSSL 2.8.0

### ISSUE THREAD

**Issue by alexhaydock** [alexhaydock/nginx-libressl-latest#1]
After updating the Dockerfile for this repo to use the newly-released LibreSSL `2.8.0`, builds are failing.

- [LibreSSL 2.8.0 Changelog](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.8.0-relnotes.txt)
- [Nginx 1.15.2 Changelog](https://nginx.org/en/CHANGES)
- [Build error output](https://hub.docker.com/r/alexhaydock/nginx-libressl-latest/builds/bduldybhbpkpjgvyvfgqhh5/)

The errors faced here are similar to those in [this StackOverflow post](https://stackoverflow.com/questions/44996759/error-when-building-nginx-docker) and it would seem that the likely culprit is something the LibreSSL team deprecated between `2.7.4` and `2.8.0` that Nginx is still expecting to be there.

For now, I think all I can do is wait for the Nginx team to update to handle the newly deprecated features.

**Comment by alexhaydock** [comment]
https://trac.nginx.org/nginx/ticket/1605

**Comment by alexhaydock** [comment]
See also: libressl-portable/portable#435

**Comment by 4a6f656c** [comment]
Just to clarify, it's not a deprecation, rather the addition of `const` to a callback function, in order to match the current OpenSSL API.

**Comment by alexhaydock** [comment]
Thanks for the clarification, @4a6f656c :+1:

**Comment by alexhaydock** [comment]
Fixed by Nginx 1.15.3
